[package]
name = "rust-cli-starter"
version = "0.1.0"
authors = ["kkpoon <noopkk@gmail.com>"]

[dependencies]
clap = "2"
hyper = "0.10"
hyper-native-tls = "0.2.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
